### ISSUE TITLE
Incorrect element blocks extraction from msh v2

### ISSUE THREAD

**Issue by cityadmirer** [qnzhou/MshIO#28] opened 2024-10-15 10:14 UTC
For msh v2 file, the `entity_tag` attribute of `ElementBlock` struct is actually the physical group tag.

**Comment by qnzhou** [comment] 2024-10-16 15:51
@cityadmirer Can you share an example?

Here is what the official spec said:

> By default, the first tag is the tag of the physical entity to which the element belongs; the second is the tag of the elementary model entity to which the element belongs;
> ...
> Gmsh and most codes using the MSH 2 format require at least the first two tags (physical and elementary tags).

When both tags are present, the following code put the second tag as `ElementBlock::entity_tag`.

https://github.com/qnzhou/MshIO/blob/8d3254b0c4408f914f4074d0f4d9be5d8beff0a3/src/load_msh_elements.cpp#L140-L150

**Comment by cityadmirer** [comment] 2024-10-17 07:24
msh files are generated using gmsh .geo script
```
Point(1) = {0, 0, 0, 1.0};
Point(2) = {1, 0, 0, 1.0};
Point(3) = {1, 1, 0, 1.0};
Point(4) = {0, 1, 0, 1.0};
Point(5) = {-1, 0, 0, 1.0};

Line(1) = {1, 2};
Line(2) = {2, 3};
Line(3) = {3, 4};
Line(4) = {4, 1};
Line(5) = {1, 5};

Curve Loop(1) = {4, 1, 2, 3};
Plane Surface(1) = {1};

Physical Curve("edge", 7) = {1, 5};
Physical Surface("membrane", 6) = {1};

Transfinite Curve{:} = 5;
Transfinite Surface{:};
Recombine Surface {:};

Mesh 2;

Mesh.MshFileVersion = 2.2;
Save "v2.msh";

Mesh.MshFileVersion = 4.1;
Save "v4.msh";
```
For the v4 file, 3 element blocks are read in with `entity_tag`s `1 5 1`, while for v2 file, they are `7 6`.

**Comment by qnzhou** [comment] 2024-10-17 20:56
Hmmm, just tested it and here is what I got:

```py
>>> import mshio
>>> v2 = mshio.load_msh("v2.msh")
>>> v4 = mshio.load_msh("v4.msh")
>>> v2.elements.entity_blocks
[ElementBlock(entity_dim=1, entity_tag=1, element_type=1, num_elements_in_block=4), ElementBlock(entity_dim=1, entity_tag=5, element_type=1, num_elements_in_block=4), ElementBlock(entity_dim=2, entity_tag=1, element_type=3, num_elements_in_block=16)]
>>> v4.elements.entity_blocks
[ElementBlock(entity_dim=1, entity_tag=1, element_type=1, num_elements_in_block=4), ElementBlock(entity_dim=1, entity_tag=5, element_type=1, num_elements_in_block=4), ElementBlock(entity_dim=2, entity_tag=1, element_type=3, num_elements_in_block=16)]
>>>
```

The entity tags for both v2 and v4 are `[1, 5, 1]`.

**Comment by qnzhou** [comment] 2024-10-21 16:15
Closing for now. @cityadmirer , feel free to reopen if you cannot reproduce my result above.

**Closed by qnzhou** 2024-10-21 16:15 UTC
